#!/bin/bash

set -eu

if [[ ${PWD##*/} != bld ]]; then
    echo "Not in the expected build directory" > /dev/stderr
    exit 1
fi

if [[ -f CMakeCache.txt ]]; then
    rm -rf *
fi

cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MODULE_PATH=~/.local/lib64/cmake -DCMAKE_INSTALL_PREFIX=~/.local #-DPYTHON_EXECUTABLE=/usr/bin/python3

make -j8
