#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

set -eux

which wget

if (( $# != 4 )); then
    echo "Usage: github-get-tarball USER-NAME REPO-NAME REVISION OUTPUT-FILE"
    exit 1
fi

USER=$1
REPO=$2
REVISION=$3
OUTPUT=$4

wget https://github.com/$USER/$REPO/tarball/$REVISION -O $OUTPUT
