#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

from plano import *

root_dir = ARGS[1]

fingerprint_1a = "Licensed to the Apache Software Foundation"
fingerprint_1b = "Licensed under the Apache License"
fingerprint_2 = "http://www.apache.org/licenses/LICENSE-2.0"

files_not_decoded = set()
files_without_licenses = set()

for path in find(root_dir):
    print("Checking {}".format(path))

    if ".svn" in path.split("/"):
        continue

    if not is_file(path):
        continue

    try:
        content = read(path)
    except UnicodeDecodeError:
        files_not_decoded.add(path)
        continue

    if (fingerprint_1a in content or fingerprint_1b in content) \
            and fingerprint_2 in content:
        continue

    files_without_licenses.add(path)

for path in sorted(files_not_decoded):
    print("Couldn't decode {}".format(path))

for path in sorted(files_without_licenses):
    print("Consider {}".format(path))
